apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Values.sharedNamespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:1234@{{ .Values.database.host }}-primary.{{ .Values.sharedNamespace }}.svc.cluster.local:5432/postgres" # BAAAAAD
  BACKEND_DATABASE_URL: "postgresql+asyncpg://postgres:1234@{{ .Values.database.host }}-primary.{{ .Values.sharedNamespace }}.svc.cluster.local:5432/postgres" # BAAAAAD
  DB_HOST: "{{ .Values.database.host }}-primary.{{ .Values.sharedNamespace }}.svc.cluster.local"
