apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Values.sharedNamespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:1234@{{ .Values.database.host }}-primary.{{ .Values.sharedNamespace }}.svc.cluster.local:5432/postgres?sslmode=disable"
  DB_HOST: "{{ .Values.database.host }}-primary.{{ .Values.sharedNamespace }}.svc.cluster.local"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "1234"
  DB_PORT: "5432"
