# version: "3.9"


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11-slim"
      target: dev
    container_name: bloom_art_backend
    ports:
      - 8000:8000
    networks:
      - bloom_art_network
    volumes:
      - type: volume
        target: /app/backend/.venv
      - type: bind
        source: ./backend
        target: /app
    depends_on:
      - db
      - redis
    environment:
      - UV_LINK_MODE=copy
    env_file:
      - .env
    image: bloom-art-backend-dev:latest

  db:
    image: postgres:15.1-alpine
    volumes:
      - bloom_art_database_data:/var/lib/postgresql/data
    networks:
      - bloom_art_network
    # ports:
    #   - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: bloom_art_redis
    # ports:
    #   - "6379:6379"
    volumes:
      - bloom_art_redis_data:/data
    networks:
      - bloom_art_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: "20-alpine"
      target: dev
    container_name: bloom_art_frontend
    ports:
      - 3000:3000
    volumes:
      - type: volume
        target: /app/node_modules
      - type: bind
        source: ./frontend
        target: /app
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    env_file:
      - .env
    networks:
    - bloom_art_network
    image: bloom-art-frontend-dev



volumes:
  bloom_art_database_data:
  bloom_art_redis_data:

networks:
  bloom_art_network:
