apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-configmap
data:
  86cJezwvheONZ_3Nx8KKBXX6ogjmaW73f6M12BlkBRc: 86cJezwvheONZ_3Nx8KKBXX6ogjmaW73f6M12BlkBRc.kgEWgLTPNmT78vzeXvMcVEAMT2eenkcnCw2wo99_Mpw
