apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tls-ingressroute
spec:
  routes:
    - kind: Rule
      match: Host(`bloom-art.chickenkiller.com`) && Path(`/.well-known/acme-challenge/86cJezwvheONZ_3Nx8KKBXX6ogjmaW73f6M12BlkBRc`)
      services:
        - kind: Service
          name: tls-service
          port: 80
          scheme: http
