apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_tls.name }}
  namespace: {{ .Values.sharedNamespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDrTCCAzKgAwIBAgISBm38AvEDxRjDg7yQ+kJKt8raMAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    NzAeFw0yNTExMjUxNDA3NDlaFw0yNjAyMjMxNDA3NDhaMCoxKDAmBgNVBAMTH215
    LWt1YmVybmV0ZXMuY2hpY2tlbmtpbGxlci5jb20wWTATBgcqhkjOPQIBBggqhkjO
    PQMBBwNCAAQO+bMfbpnJ8RKULhtY6pLgmnlwAM4KO2ZAaFpFE48rLCKvFo58yucS
    DYqY+2ePSUXUzeK54mzzgT7/sjxVbPzeo4ICLjCCAiowDgYDVR0PAQH/BAQDAgeA
    MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0G
    A1UdDgQWBBSDY3TA3L9Iu8wYT4Ml32pcsbzWRjAfBgNVHSMEGDAWgBSuSJ7chx1E
    oG/aouVgdAR4wpwAgDAyBggrBgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6
    Ly9lNy5pLmxlbmNyLm9yZy8wKgYDVR0RBCMwIYIfbXkta3ViZXJuZXRlcy5jaGlj
    a2Vua2lsbGVyLmNvbTATBgNVHSAEDDAKMAgGBmeBDAECATAtBgNVHR8EJjAkMCKg
    IKAehhxodHRwOi8vZTcuYy5sZW5jci5vcmcvOTEuY3JsMIIBBQYKKwYBBAHWeQIE
    AgSB9gSB8wDxAHYASZybad4dfOz8Nt7Nh2SmuFuvCoeAGdFVUvvp6ynd+MMAAAGa
    u40fswAABAMARzBFAiBufNv1Urn1vUfAPTy/zl4snnKNy7rv02xGrBF5Q6xU2wIh
    APFjQC2TwCwlFFgM1M3QnamrfHMBEBZmsIeM97mwOxriAHcAGYbUxyiqb/66A294
    Kk0BkarOLXIxD67OXXBBLSVMx9QAAAGau40fsgAABAMASDBGAiEAnp+0ZMLfKURB
    k+RTreTr/6hooHwhwLS0pP0WhhmXc6UCIQDbna8RuhKJQSKPj9t23906zSB9mLnG
    gWb94lZ2DM5XsTAKBggqhkjOPQQDAwNpADBmAjEAvWa7sIYoadMUNpSxw77cYSZl
    MYuaJxzU4S53EXMhxI5eAj0v06sDhPV+6qN0PZb9AjEArmkxB7lCQT57Q9N1w0/K
    JEAgD/Qg9AfHG14k9LrB4jGERdq3TkEY96JkOEWbgWkX
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEVzCCAj+gAwIBAgIRAKp18eYrjwoiCWbTi7/UuqEwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
    WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCRTcwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAARB6AST
    CFh/vjcwDMCgQer+VtqEkz7JANurZxLP+U9TCeioL6sp5Z8VRvRbYk4P1INBmbef
    QHJFHCxcSjKmwtvGBWpl/9ra8HW0QDsUaJW2qOJqceJ0ZVFT3hbUHifBM/2jgfgw
    gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
    ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSuSJ7chx1EoG/aouVgdAR4
    wpwAgDAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB
    AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g
    BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu
    Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAjx66fDdLk5ywFn3CzA1w1qfylHUD
    aEf0QZpXcJseddJGSfbUUOvbNR9N/QQ16K1lXl4VFyhmGXDT5Kdfcr0RvIIVrNxF
    h4lqHtRRCP6RBRstqbZ2zURgqakn/Xip0iaQL0IdfHBZr396FgknniRYFckKORPG
    yM3QKnd66gtMst8I5nkRQlAg/Jb+Gc3egIvuGKWboE1G89NTsN9LTDD3PLj0dUMr
    OIuqVjLB8pEC6yk9enrlrqjXQgkLEYhXzq7dLafv5Vkig6Gl0nuuqjqfp0Q1bi1o
    yVNAlXe6aUXw92CcghC9bNsKEO1+M52YY5+ofIXlS/SEQbvVYYBLZ5yeiglV6t3S
    M6H+vTG0aP9YHzLn/KVOHzGQfXDP7qM5tkf+7diZe7o2fw6O7IvN6fsQXEQQj8TJ
    UXJxv2/uJhcuy/tSDgXwHM8Uk34WNbRT7zGTGkQRX0gsbjAea/jYAoWv0ZvQRwpq
    Pe79D/i7Cep8qWnA+7AE/3B3S/3dEEYmc0lpe1366A/6GEgk3ktr9PEoQrLChs6I
    tu3wnNLB2euC8IKGLQFpGtOO/2/hiAKjyajaBP25w1jF0Wl8Bbqne3uZ2q1GyPFJ
    YRmT7/OXpmOH/FVLtwS+8ng1cAmpCujPwteJZNcDG0sF2n/sc0+SQf49fdyUK0ty
    +VUwFj9tmWxyR/M=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgcHTtv1ie28Ll0R9D
    5M4ILCQ4k5w9pP1ilfeQdOk7m3OhRANCAAQO+bMfbpnJ8RKULhtY6pLgmnlwAM4K
    O2ZAaFpFE48rLCKvFo58yucSDYqY+2ePSUXUzeK54mzzgT7/sjxVbPze
    -----END PRIVATE KEY-----
