apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_tls.name }}
  namespace: {{ .Values.sharedNamespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDpTCCAyqgAwIBAgISBl2Gnx9LAVkFPE2SsIPG0qLFMAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    ODAeFw0yNTExMjUxNzIwMTJaFw0yNjAyMjMxNzIwMTFaMCYxJDAiBgNVBAMTG2Js
    b29tLWFydC5jaGlja2Vua2lsbGVyLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEH
    A0IABGioMZsvyfGepDQOmLcrZ/UXaAIc0VroPR8EGR9K9dR5MPn2LYJDanPC47Ia
    kTFo3ncQgvqPLyehIRLuM2I6U+2jggIqMIICJjAOBgNVHQ8BAf8EBAMCB4AwHQYD
    VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
    BBYEFIlGI+SjZOb8tAVIBtvw9uZ6x9fGMB8GA1UdIwQYMBaAFI8NE6L2Ln7RUGwz
    GDhdWY4jcpHKMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL2U4
    LmkubGVuY3Iub3JnLzAmBgNVHREEHzAdghtibG9vbS1hcnQuY2hpY2tlbmtpbGxl
    ci5jb20wEwYDVR0gBAwwCjAIBgZngQwBAgEwLQYDVR0fBCYwJDAioCCgHoYcaHR0
    cDovL2U4LmMubGVuY3Iub3JnLzcwLmNybDCCAQUGCisGAQQB1nkCBAIEgfYEgfMA
    8QB3AGQRxGykEuyniRyiAi4AvKtPKAfUHjUnq+r+1QPJfc3wAAABmrw9RGUAAAQD
    AEgwRgIhAOzXA/wjVqLWu/JbEf2h+3TOubBvmQlgs6qrNsmG1XRjAiEAvfW42Fy7
    MiFlzqySvpBrOLN74yZHyadthwYLya9uie4AdgCWl2S/VViXrfdDh2g3CEJ36fA6
    1fak8zZuRqQ/D8qpxgAAAZq8PUSrAAAEAwBHMEUCIHYGML/iRJNqJgU6SZLhBOB9
    48DgF5iiJq3zrlfrWlpIAiEAjifIYIIUECbLeAAUYOz3NVf8Wz66Mq2bVvfqBmYC
    zM0wCgYIKoZIzj0EAwMDaQAwZgIxAL2fkTJ1WPh8XFwPj7AMidovrVopZjbcm74/
    ZVjy0rZjfly9UwF2B2gRQIUlLL04awIxANq57VxfsikwWGlMbMqKUq/ZLVxk/YJu
    mJNkOuJR8XXgUr76G6CrpmQmrIz+2vhlgA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEVjCCAj6gAwIBAgIQY5WTY8JOcIJxWRi/w9ftVjANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
    Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
    Fw0yNzAzMTIyMzU5NTlaMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
    bmNyeXB0MQswCQYDVQQDEwJFODB2MBAGByqGSM49AgEGBSuBBAAiA2IABNFl8l7c
    S7QMApzSsvru6WyrOq44ofTUOTIzxULUzDMMNMchIJBwXOhiLxxxs0LXeb5GDcHb
    R6EToMffgSZjO9SNHfY9gjMy9vQr5/WWOrQTZxh7az6NSNnq3u2ubT6HTKOB+DCB
    9TAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMB
    MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFI8NE6L2Ln7RUGwzGDhdWY4j
    cpHKMB8GA1UdIwQYMBaAFHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEB
    BCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzATBgNVHSAE
    DDAKMAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5j
    ci5vcmcvMA0GCSqGSIb3DQEBCwUAA4ICAQBnE0hGINKsCYWi0Xx1ygxD5qihEjZ0
    RI3tTZz1wuATH3ZwYPIp97kWEayanD1j0cDhIYzy4CkDo2jB8D5t0a6zZWzlr98d
    AQFNh8uKJkIHdLShy+nUyeZxc5bNeMp1Lu0gSzE4McqfmNMvIpeiwWSYO9w82Ob8
    otvXcO2JUYi3svHIWRm3+707DUbL51XMcY2iZdlCq4Wa9nbuk3WTU4gr6LY8MzVA
    aDQG2+4U3eJ6qUF10bBnR1uuVyDYs9RhrwucRVnfuDj29CMLTsplM5f5wSV5hUpm
    Uwp/vV7M4w4aGunt74koX71n4EdagCsL/Yk5+mAQU0+tue0JOfAV/R6t1k+Xk9s2
    HMQFeoxppfzAVC04FdG9M+AC2JWxmFSt6BCuh3CEey3fE52Qrj9YM75rtvIjsm/1
    Hl+u//Wqxnu1ZQ4jpa+VpuZiGOlWrqSP9eogdOhCGisnyewWJwRQOqK16wiGyZeR
    xs/Bekw65vwSIaVkBruPiTfMOo0Zh4gVa8/qJgMbJbyrwwG97z/PRgmLKCDl8z3d
    tA0Z7qq7fta0Gl24uyuB05dqI5J1LvAzKuWdIjT1tP8qCoxSE/xpix8hX2dt3h+/
    jujUgFPFZ0EVZ0xSyBNRF3MboGZnYXFUxpNjTWPKpagDHJQmqrAcDmWJnMsFY3jS
    u1igv3OefnWjSQ==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgi2pAp7dlGgCNAOOR
    +W410Mqaylayf7DYI76QSB+DYgahRANCAARoqDGbL8nxnqQ0Dpi3K2f1F2gCHNFa
    6D0fBBkfSvXUeTD59i2CQ2pzwuOyGpExaN53EIL6jy8noSES7jNiOlPt
    -----END PRIVATE KEY-----
