apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secretName }}
  namespace: {{ .Values.sharedNamespace }}
type: Opaque
stringData:
  REDIS_URL: "redis://database-redis-master.{{ .Values.sharedNamespace }}.svc.cluster.local:6379"
