apiVersion: v2
name: application-umbrella-chart
description: Application umbrella chart of bloom-art
type: application

version: 1.0.0

appVersion: "1.0.0"

maintainers:
  - name: vladyslav-yarko
    email: vladislavv44444@gmail.com

annotations:
  org.opencontainers.image.source: "https://github.com/vladyslav-yarko/bloom-art"
  org.opencontainers.image.maintainer: "vladyslav-yarko"

home: "https://github.com/vladyslav-yarko/bloom-art"
sources:
  - "https://github.com/vladyslav-yarko/bloom-art"


dependencies:
  - name: common-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vladyslav-yarko/bloom-art"
  - name: postgresql-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vladyslav-yarko/bloom-art"
  - name: redis-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vladyslav-yarko/bloom-art"
  - name: backend-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vladyslav-yarko/bloom-art"
  - name: frontend-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vladyslav-yarko/bloom-art"
  