apiVersion: v2
name: my-kubernetes-umbrella-chart
description: Umbrella chart of my-kubernetes
type: application

# Chart version — updates when chart templates/values change
version: 1.0.0

# App version — the app's actual version (image tag, etc)
appVersion: "1.0.0"

# This matches your Docker LABEL maintainer
maintainers:
  - name: vlad-yarko
    email: vladislavv44444@gmail.com

# These are your Docker labels but in Helm
annotations:
  org.opencontainers.image.source: "https://github.com/vlad-yarko/my-kubernetes"
  org.opencontainers.image.maintainer: "vlad-yarko"

# For documentation / searching
home: "https://github.com/vlad-yarko/my-kubernetes"
sources:
  - "https://github.com/vlad-yarko/my-kubernetes"
# keywords:
#   - backend
#   - kubernetes
#   - helm
#   - my-app

dependencies:
  - name: common-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vlad-yarko/my-kubernetes"
  - name: database-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vlad-yarko/my-kubernetes"
  - name: backend-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vlad-yarko/my-kubernetes"
  - name: frontend-chart
    version: 1.0.0
    repository: "oci://ghcr.io/vlad-yarko/my-kubernetes"
  