sharedNamespace: bloom-art-application
applicationHost: bloom-art.chickenkiller.com


backend:
  middleware:
    name: backend-middleware
    prefix: /api

  deployment:
    name: backend-deployment
    podName: backend-pod
    replicas: 2
    containerName: backend-container
    image: ghcr.io/vladyslav-yarko/bloom-art-backend:prod
    containerPort: 8000

  service:
    name: backend-service
    port: 8000

  ingressRoute:
    name: backend-ingressroute
  
  secretName: backend-secret

  job:
    name: backend-job
    backoffLimit: 3


database:
  secretName: database-secret

secret_tls:
  name: secret-tls

middleware_tls:
  name: middleware-tls

redis:
  secretName: redis-secret
