sharedNamespace: bloom-art-application

auth:
  enabled: true
  password: "1234"

# architecture: replication

# replica:
#   replicaCount: 2


# fullnameOverride: "database-redis"

redis:
  fullnameOverride: "database-redis"
  secretName: redis-secret
  architecture: "standalone"
  # architecture: replication
  # replica:
  #   replicaCount: 1
  auth:
    enabled: true
    password: "1234"
