apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deployment.name }}
  namespace: {{ .Values.sharedNamespace }}
  labels:
    app: {{ .Values.backend.deployment.name }}
spec:
  replicas: {{ .Values.backend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.deployment.podName }}
    spec:
      containers:
        - name: {{ .Values.backend.deployment.containerName }}
          image: {{ .Values.backend.deployment.image }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ .Values.database.secretName }}
          ports:
            - containerPort: {{ .Values.backend.deployment.containerPort }}
              protocol: TCP
          # readinessProbe:
          #   initialDelaySeconds: 35
          #   periodSeconds: 15
          #   timeoutSeconds: 15
          #   failureThreshold: 2
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.backend.deployment.containerPort }}
          # livenessProbe:
          #   initialDelaySeconds: 35
          #   periodSeconds: 15
          #   timeoutSeconds: 15
          #   failureThreshold: 2
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.backend.deployment.containerPort }}
          resources:
            requests:
              memory: "30Mi"
              cpu: "50m"
            limits:
              memory: "60Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
