apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.backend.ingressRoute.name }}
  namespace: {{ .Values.sharedNamespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.applicationHost }}`) && PathPrefix(`{{ .Values.backend.middleware.prefix }}`)
      middlewares:
        - name: {{ .Values.backend.middleware.name }}
        - name: {{ .Values.middleware_tls.name }}
      services:
        - kind: Service
          name: {{ .Values.backend.service.name }}
          port: {{ .Values.backend.service.port }}
          scheme: http
