apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.backend.job.name }}
spec:
  backoffLimit: {{ .Values.backend.job.backoffLimit }}
  template:
    spec:
      initContainers:
        - name: {{ .Values.backend.job.name }}-init
          image: postgres:15
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h "$HOST" -p "5432"; do
                sleep 1;
              done
              echo "PostgreSQL is up!"
          env:
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.secretName }}
                key: DB_HOST
      containers:
      - name: migrate
        image: {{ .Values.backend.deployment.image }}
        command: ["uv", "run", "python"]
        args: ["manage.py", "migrate"]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ .Values.database.secretName }}
        - secretRef:
            name: {{ .Values.backend.secretName }}
        - secretRef:
            name: {{ .Values.redis.secretName }}
      restartPolicy: OnFailure
