apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.sharedNamespace }}
type: Opaque
stringData:
  NOVA_API_KEY : "7f188636ae46cbfae03f9fdc3f64a6f6"
  NOVA_CITY_SENDER : "615019a2-6c11-11e1-a983-0026b97ed48a"
  NOVA_SENDER_COUNTERPARTY_REF : "0698a528-577f-11f0-a1d5-48df37b921da"
  NOVA_SENDER_CONTACT_REF : "06991c45-577f-11f0-a1d5-48df37b921da"
  NOVA_SENDER_ADDRESS : "1ec09d6e-e1c2-11e3-8c4a-0050568002cf"
  NOVA_PHONE_NUMBER : "+380958005215"
  NOVA_BANK_CARD : "4314140208899275"
  NOVA_FIRST_NAME : "Євген"
  NOVA_LAST_NAME : "Дводненко"
