apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.sharedNamespace }}
spec:
  selector:
    app: {{ .Values.backend.deployment.podName }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.deployment.containerPort }}
