apiVersion: v2
name: postgresql-chart
description: PostgreSQL chart of bloom-art
type: application

version: 1.0.0

appVersion: "1.0.0"

maintainers:
  - name: vladyslav-yarko
    email: vladislavv44444@gmail.com

annotations:
  org.opencontainers.image.source: "https://github.com/vladyslav-yarko/bloom-art"
  org.opencontainers.image.maintainer: "vladyslav-yarko"

home: "https://github.com/vladyslav-yarko/bloom-art"
sources:
  - "https://github.com/vladyslav-yarko/bloom-art"

dependencies:
  - name: postgresql
    version: 15.4.1
    repository: "https://charts.bitnami.com/bitnami"
