apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
  namespace: {{ .Values.sharedNamespace }}
  labels:
    app: {{ .Values.frontend.deployment.name }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.podName }}
    spec:
      containers:
        - name: {{ .Values.frontend.deployment.containerName }}
          image: {{ .Values.frontend.deployment.image }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.frontend.configmap.name }}
          ports:
            - containerPort: {{ .Values.frontend.deployment.containerPort }}
              protocol: TCP
          # readinessProbe:
          #   initialDelaySeconds: 35
          #   periodSeconds: 15
          #   timeoutSeconds: 15
          #   failureThreshold: 2
          #   httpGet:
          #     path: /ping
          #     port: {{ .Values.frontend.deployment.containerPort }}
          # livenessProbe:
          #   initialDelaySeconds: 35
          #   periodSeconds: 15
          #   timeoutSeconds: 15
          #   failureThreshold: 2
          #   httpGet:
          #     path: /ping
          #     port: {{ .Values.frontend.deployment.containerPort }}
          resources:
            requests:
              memory: "30Mi"
              cpu: "50m"
            limits:
              memory: "80Mi"
              cpu: "150m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
