apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.frontend.ingressRoute.name }}
  namespace: {{ .Values.sharedNamespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.applicationHost }}`) && PathPrefix("/")
      middlewares:
        - name: {{ .Values.middleware_tls.name }}
      services:
        - kind: Service
          name: {{ .Values.frontend.service.name }}
          port: {{ .Values.frontend.service.port }}
          scheme: http
