apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.grafana.service.name }}
  namespace: {{ .Values.sharedNamespace }}
spec:
  selector:
    app: {{ .Values.monitoring.grafana.deployment.podName }}
  ports:
    - port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: {{ .Values.monitoring.grafana.deployment.containerPort }}
