apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.loki.service.name }}
  namespace: {{ .Values.sharedNamespace }}
spec:
  selector:
    app: {{ .Values.monitoring.loki.statefulset.podName }}
  ports:
    - port: {{ .Values.monitoring.loki.service.port }}
      targetPort: {{ .Values.monitoring.loki.statefulset.containerPort }}
