apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware_tls.name }}
  namespace: {{ .Values.sharedNamespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
