apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.monitoring.prometheus.config.name }}
  namespace: {{ .Values.sharedNamespace }}
data:
  {{ .Values.monitoring.prometheus.config.fileName }}: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "backend"
        metrics_path: /api/metrics
        static_configs:
          - targets: ["http://backend-service.{{ .Values.applicationNamespace }}.svc.cluster.local:8000"]

      - job_name: "postgresql"
        static_configs:
          - targets: ["http://postgresql-exporter-service.{{ .Values.applicationNamespace }}.svc.cluster.local:9187"]

      - job_name: "redis"
        static_configs:
          - targets: ["http://redis-exporter-service.{{ .Values.applicationNamespace }}.svc.cluster.local:9121"]
