apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.monitoring.promtail.deamonset.name }}
  namespace: {{ .Values.sharedNamespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.monitoring.promtail.deamonset.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.monitoring.promtail.deamonset.podName }}
    spec:
      serviceAccountName: promtail-account
      containers:
      - name: {{ .Values.monitoring.promtail.deamonset.containerName }}
        image: grafana/promtail:latest
        args:
          - -config.file=/etc/promtail/{{ .Values.monitoring.promtail.config.fileName }}
        volumeMounts:
          - name: config
            mountPath: /etc/promtail
          - name: varlog
            mountPath: /var/log
          - name: varlibcontainers
            mountPath: /var/lib/containers
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Values.monitoring.promtail.config.name }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibcontainers
          hostPath:
            path: /var/log/containers
