sharedNamespace: bloom-art-application
applicationHost: bloom-art.chickenkiller.com


frontend:
  configmap:
    name: frontend-configmap

  deployment:
    name: frontend-deployment
    replicas: 2
    podName: frontend-pod
    containerName: frontend-container
    image: ghcr.io/vladyslav-yarko/bloom-art-frontend:prod
    containerPort: 3000

  service:
    name: frontend-service
    port: 3000

  ingressRoute:
    name: frontend-ingressroute

secret_tls:
  name: secret-tls

middleware_tls:
  name: middleware-tls
